version: "3.8"

services:
  ros1-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros1_dev_container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../:/workspace/src/rgbd-camera-interface
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash
